
" Colors
" The main colors of the editor
colorscheme pablo " colors for a night in the wild 
set background=light " usually, I use a dark background, sometimes I prefer a light one.

" Enable syntax highlighting
syntax enable

" Spaces and tabs
" Optimized for Python
set tabstop=4       " number of visual spaces per TAB
set softtabstop=4   " number of spaces in tab when editing
set expandtab       " tabs are spaces

" More UI
set number              " show line numbers
set showmatch           " highlight matching [{()}]
