# Configure Starship prompt

[hostname]
ssh_only = false
style = "bold blue"

[directory]
style = "bold pink"

[git_branch]
symbol = "🌱 "
style = "bold green"

[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"
