# Configure Starship prompt

[hostname]
ssh_only = false
style = "bold blue"


[git_branch]
symbol = "🌱 "
style = "bold green"

[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"

[env_var]
variable = "STARSHIP_SHELL"
default = "unknown shell"
